version: '3.1'

services: 
  mongo:
    image: mongo:4.4.4
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: movies
  app:
    image: app_movies
    build:
      dockerfile: ./Dockerfile
      context: ./app
    volumes:
      - ./app:/app
    command: uvicorn main:app --reload --workers 2 --host 0.0.0.0 --port 80
    ports:
      - 8000:80
    depends_on:
      - mongo
